#! /bin/bash
cd /home/zzf/YCSB/
/home/zzf/YCSB/bin/ycsb load memcached -P /home/zzf/YCSB/workloads/workloadMagi -p "memcached.hosts=127.0.0.1" -p "memcached.port=11211"
#7 9
/home/zzf/YCSB/bin/ycsb run memcached -P /home/zzf/YCSB/workloads/workloadMagi -p "memcached.hosts=127.0.0.1" -p "memcached.port=11211" -threads 10 -p "operationcount=99999999"